services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: tododb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  server:
    build:
      context: .
    command: >
      bash -c "poetry run flask db upgrade && poetry run flask run --host=0.0.0.0"
    env_file:
      - ./.env
    environment:
      DATABASE_HOST: db
    depends_on:
      - db
    ports:
      - "5000:5000"

volumes:
  postgres_data: